import { NextResponse } from "next/server";
import { getAdminSession } from "@/lib/admin-auth";
import { createClient } from "@supabase/supabase-js";

export const dynamic = "force-dynamic";

export async function GET() {
  const admin = await getAdminSession();
  if (!admin) return NextResponse.json({ ok: false, error: "Unauthorized." }, { status: 401 });

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  const results: Record<string, unknown> = {
    has_service_key: !!serviceKey,
    has_anon_key: !!anonKey,
    supabase_url: url ? url.slice(0, 30) + "..." : "MISSING",
  };

  // Try with service role key
  if (serviceKey) {
    const sb = createClient(url, serviceKey, { auth: { persistSession: false } });

    // SELECT
    const { data, error, count } = await sb.from("tickets").select("*", { count: "exact" }).limit(5);
    results.service_role_select = { error: error?.message ?? null, code: error?.code ?? null, count, rows: data?.length ?? 0, sample: data };

    // TEST INSERT — no user_id
    const { data: ins, error: insErr } = await sb.from("tickets").insert({
      guest_username: "debug-test",
      subject: "Debug Test Ticket",
      message: "Auto-generated by debug endpoint. Safe to delete.",
      status: "open",
    }).select().single();
    results.service_role_insert = { error: insErr?.message ?? null, code: insErr?.code ?? null, inserted_id: ins?.id ?? null };

    // Clean up test row
    if (ins?.id) await sb.from("tickets").delete().eq("id", ins.id);
  }

  // Try with anon key — insert test
  if (anonKey) {
    const sb = createClient(url, anonKey, { auth: { persistSession: false } });
    const { data, error, count } = await sb.from("tickets").select("*", { count: "exact" }).limit(5);
    results.anon_key_select = { error: error?.message ?? null, code: error?.code ?? null, count, rows: data?.length ?? 0 };

    const { data: ins2, error: insErr2 } = await sb.from("tickets").insert({
      guest_username: "debug-anon",
      subject: "Anon Debug Ticket",
      message: "Auto-generated. Safe to delete.",
      status: "open",
    }).select().single();
    results.anon_key_insert = { error: insErr2?.message ?? null, code: insErr2?.code ?? null, inserted_id: ins2?.id ?? null };
    if (ins2?.id) await sb.from("tickets").delete().eq("id", ins2.id);
  }

  return NextResponse.json(results);
}
