-- Create the minigame_spins table for Whack-a-Mole leaderboard
CREATE TABLE IF NOT EXISTS public.minigame_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id TEXT NOT NULL,
    username TEXT NOT NULL,
    avatar_url TEXT,
    score INTEGER NOT NULL DEFAULT 0,
    prize_name TEXT NOT NULL,
    prize_rarity TEXT NOT NULL,
    spun_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.minigame_spins ENABLE ROW LEVEL SECURITY;

-- Create policies
-- 1. Allow everyone to read scores (for the leaderboard)
CREATE POLICY "Allow public read access to minigame scores" 
ON public.minigame_spins FOR SELECT 
USING (true);

-- 2. Allow system (service role) to insert/update
-- (Admin client used in API bypasses RLS, but it's good practice)

-- Create an index for the leaderboard performance
CREATE INDEX IF NOT EXISTS minigame_spins_score_idx ON public.minigame_spins (score DESC);
CREATE INDEX IF NOT EXISTS minigame_spins_discord_id_idx ON public.minigame_spins (discord_id);
